language: node_js
node_js:
  - 12
os:
  - windows
  - osx
  - linux
osx_image: xcode10.2
git:
  depth: false
script:
  - "bash ./build.sh"
before_deploy:	
  - git config --local user.name "RobinSchapendonk"	
  - git config --local user.email "ytrobinsch2@gmail.com"	
  - export TRAVIS_TAG=v0.0.2
  - git tag $TRAVIS_TAG
deploy:	
  repo: RobinSchapendonk/Chattin
  provider: releases	
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./dist/*
  skip_cleanup: true	
  draft: true 